### ISSUE TITLE
Mostrar apenas amigos na hora de criar canal

### ISSUE THREAD

**Issue by ichmi** [tenis-de-mesa/ft_transcendence#101]
A partir da inclusao da PR #98 do Lucas, podemos dar inicio ao filtro de inclusao de usuarios da friend list apenas, durante a criacao de um novo canal. Hoje estamos listando todos os usuarios do sistema, a ideia eh que a gente so tenha acessos aos usuarios da lista de amigos, right?
![frrrr](https://github.com/tenis-de-mesa/ft_transcendence/assets/56981089/8361d93a-51d8-4e22-8856-4d5cb5c57560)

**Comment by erick-medeiros** [comment]
Vou colocar isso dentro d chats checklist #65
