### ISSUE TITLE
Erro ao invocar o loader antes de estar autenticado

### ISSUE THREAD

**Issue by ichmi** [tenis-de-mesa/ft_transcendence#102]
Esse erro ja eh conhecido nosso a algum tempo. Isso se da pelo fato da gente invocar implicitamente o loader `loadRootUser` sem estar previamente autenticado. Seria interessante cuidar esse tipo de erro, pois caso haja algum ponto da regua que cheque por warnings/errors no console, a gente nao rode por bobagem:

![una1](https://github.com/tenis-de-mesa/ft_transcendence/assets/56981089/dc84669e-7a0d-4484-b012-cd7c3f0b0b3d)

**Comment by LucasKuhn** [comment]
Conferi aqui - tanto o Fetch quanto o XHR fazem o log desse erro automaticamente depois do request quando ele é 401. 
Não queria mudar a guard, faz sentido ela dar 401 mesmo.

Então pra mim o que parece mais clean é uma rota separada, tipo GET `/users/isAuthenticated` que ao invés de retornar um erro retorna 200 - e diz no corpo se tá ou não autenticado
```ts
@Get('isAuthenticated')
  async isAuthenticated(@Req() request: Request) {
    // Se estiver autencitado 
    return { authenticated: true };
    // Se não estiver 
    return { authenticated: false };
  }

```
Aí o `loadRootUser` checa essa rota antes de pegar o user 
```ts
export async function loadRootUser() {
  const authCheck = await fetch(`http://localhost:3001/users/isAuthenticated`, {
    credentials: "include",
  });
  const authStatus = await authCheck.json();
  if (!authStatus.authenticated) {
    return null;
  }
  return await fetch(`http://localhost:3001/users/me`, {
    credentials: "include",
  });
}
```
Só acho que preciso do @araggohnxd pra fazer fazer essa rota isAuthenticated, fiz um pseudo codigo aqui em cima 👯‍♂️

**Comment by araggohnxd** [comment]
Acho que o correto mesmo seria tratar os erros dos loaders num geral com `errorElement`s. No caso da autenticação, agora temos o `RequireAuth` que, teoricamente, lida com isso pra gente.

Abri uma nova issue pros loaders em específico: #130.

**Comment by LucasKuhn** [comment]
> Acho que o correto mesmo seria tratar os erros dos loaders num geral com `errorElement`s. No caso da autenticação, agora temos o `RequireAuth` que, teoricamente, lida com isso pra gente.
> 
> 
> 
> Abri uma nova issue pros loaders em específico: #130.

Acho que não é nem isso de estrutura o problema Matheus, essa issue é mais sobre o fato de dar o erro no console 
Isso pelo que testei não importa se é fetch ou axios, sempre que uma request retorna 403 o erro é printado automaticamente no console

**Comment by LucasKuhn** [comment]
Ai mesmo movendo pra um errorelement ou requireauth, se fizer um request para /users/me vai printar um erro no console
