### ISSUE TITLE
Tratamento de erro dos loaders

### ISSUE THREAD

**Issue by araggohnxd** [tenis-de-mesa/ft_transcendence#130]
Atualmente, se um loader falha, o site só meio que quebra, as vezes vai pra ErrorBoundary com código 500, as vezes só para de funcionar mesmo. Existem formas de [tratar erros provenientes dos loaders](https://reactrouter.com/en/main/route/error-element).

**Comment by LucasKuhn** [comment]
Nessa mesma docs fala de error bubbling - então se algum filho lançar algum erro vai dar um bubble up e chegar no ErrorBoundary da root 
```tsx
<Route path="/" element={<Root />} errorElement={<ErrorBoundary />}>
```
<img width="605" alt="image" src="https://github.com/tenis-de-mesa/ft_transcendence/assets/26127185/ad3f1fce-f6b6-4060-ac3f-f6b2d65fc978">

Tecnicamente isso é um tratamento de erro 🙂

Se tiver algum loader que acha necessário lançar algum erro específico, acho que gente pode abrir uma outra PC mais específica pra situação
