### ISSUE TITLE
Poder criar canais (chat room) 

### ISSUE THREAD

**Issue by LucasKuhn** [tenis-de-mesa/ft_transcendence#44]
- The user should be able to create channels (chat rooms) that can be either public, or private, or protected by a password.

**Comment by araggohnxd** [comment]
# Objetivos
- [ ] Possibilidade de criar chats de mensagem direta.
- Funcionalidades:
  - [ ] Criar chat consigo mesmo cria nome com seu nick + "(You)" (ex.: "maolivei (You)");
  - [ ] Criar chat com outro usuário cria nome com o nick do outro (ex.: "lalex-ku");
  - [ ] Chats de mensagem direta só podem ter dois membros;
  - [ ] Chats de mensagem direta são naturalmente privados;
  - [ ] Chats de mensagem direta só são criados quando um dos usuários envia a primeira mensagem;
  - [ ] Se um chat já existir entre você e o outro usuário (ou só você), criar um novo chat te redireciona para o chat existente.
- [ ] Possibilidade de criar chats em grupo (canais).
- Funcionalidades:
  - [ ] Canais podem ser criados com 1 ou mais usuários;
  - [ ] O nome do canal pode ser escolhido pelo usuário no momento da criação;
  - [ ] Uma lista de amigos do usuário deve ser exibida no momento de criação;
  - [ ] Uma barra de pesquisa para filtrar amigos deve ser exibida no momento de criação;
  - [ ] Canais tem diferentes tipos de acesso: público, privado ou protegido:
    - [ ] Canais públicos devem poder ser acessados na lista de chats e qualquer usuário deve conseguir entrar;
    - [ ] Canais privados só podem membros adicionados no momento da criação e não são exibidos na lista de chats;
    - [ ] Canais protegidos são como os públicos, porém necessitam de uma senha para serem acessados.
  - [ ] Membros de canal tem diferentes cargos: membro (comum), administrador e dono:
    - [ ] Membros comuns, administradores e dono podem enviar e receber mensagens no canal;
    - [ ] Administradores e dono podem expulsar membros, alterar o status dos membros comuns e o nome do canal;
    - [ ] Dono pode expulsar administradores e alterar o status dos administradores;
    - [ ] Dono é um cargo único e pertence ao usuário que criou o canal;
    - [ ] Dono pode nomear membros comuns como administradores;
    - [ ] Dono pode excluir o canal.
  - [ ]  Membros de canal tem diferentes status: ativo, mutado e banido:
    - [ ] Usuários ativos não tem nenhuma restrição de funcionalidades além das do seu próprio cargo;
    - [ ] Usuários mutados não podem enviar mensagens no canal por um determinado período, mas podem receber;
    - [ ] Usuários banidos tem todas as suas ações restringidas dentro do canal, incluindo receber mensagens.

## Nice to have:
- [ ] Administradores podem nomear membros comuns como administradores;
- [ ] Poder definir um tempo para os status de banido, assim como mutado (ex.: banido por 1 hora, 1 dia, permanentemente, etc.);
- [ ] Poder convidar novos membros para canais (não depender do usuário entrar sozinho ou ser inserido na criação);
- [ ] Poder convidar usuários para canais protegidos sem a necessidade de senha.

## Precisa pensar como vai ser:
- [ ] Usuários expulsos devem ter alguma condição especial que os impede de reentrar em canais públicos e protegidos;
- [ ] Usuários banidos ainda são membros, mesmo que banidos? E usuários expulsos?

#

Sintam-se livres para adicionar mais coisas, com certeza deixei passar alguma parte da lógica.
@LucasKuhn @erick-medeiros @ichmi

**Comment by LucasKuhn** [comment]
> O nome do canal pode ser escolhido pelo usuário no momento da criação
Talvez primeiro cria, depois edita o nome -> Discord é assim, seleciona os usuários, cria a DM em grupo, depois dá pra editar o nome do grupo se quiser

**Comment by LucasKuhn** [comment]
Que tal abrir uma PR com o que ta feito aí @araggohnxd ? 
Acho que teu branch já checa esses 2 pontos
- [x]  Possibilidade de criar chats em grupo (canais).
- [x]  Uma lista de amigos do usuário deve ser exibida no momento de criação;

E aí separamos o resto em novas issues com PRs menores
