### ISSUE TITLE
Vulnerabilidade na rota de DELETE de usuários

### ISSUE THREAD

**Issue by araggohnxd** [tenis-de-mesa/ft_transcendence#52]
Atualmente, qualquer usuário autenticado que tenha conhecimento do `User.id` de outro usuário consegue deletá-lo.

https://github.com/tenis-de-mesa/ft_transcendence/blob/6df77bd8ab1ac13299a5238a8fcdbad8a71c6f19/backend/src/users/users.controller.ts#L45-L49

**Comment by araggohnxd** [comment]
aliás, isso é realmente um problema? pq só é uma vulnerabilidade se a gente expor essa rota pro usuário. a fim de desenvolvimento é bom ter uma rota assim pra facilitar nossa vida.

@erick-medeiros @LucasKuhn @ichmi oq acham?

**Comment by LucasKuhn** [comment]
Se vai ajudar durante o desenvolvimento, por mim a gente fecha a issue e coloca pra fazer lá no final

**Comment by erick-medeiros** [comment]
> Se vai ajudar durante o desenvolvimento, por mim a gente fecha a issue e coloca pra fazer lá no final

Ai já vai estar desenvolvido hehe

**Comment by erick-medeiros** [comment]
Acredito que não dar trabalho só temos que lembrar de remover depois
