### ISSUE TITLE
Enviar mensagens muito rápido gera um erro

### ISSUE THREAD

**Issue by LucasKuhn** [tenis-de-mesa/ft_transcendence#57]
https://github.com/tenis-de-mesa/ft_transcendence/assets/26127185/9bae9399-e3cf-48da-92a0-9f7e9c16a0b4

- Talvez quando envia mensagem rápido de mais, envia uma mensagem como null 
- Talvez a função que chama no action não tá completando e não tem um fallback pra retornar null

**Comment by araggohnxd** [comment]
o problema é enviar mensagem vazia mesmo
inclusive, no `chat/new`, se mandar mensagem vazia o chat eh criado. parece contra intuitivo

**Comment by erick-medeiros** [comment]
Consegui enviar várias mensagens
E tive problemas para enviar mensagens vazias
