### ISSUE TITLE
Automatizar a checagem de barel export

### ISSUE THREAD

**Issue by LucasKuhn** [tenis-de-mesa/ft_transcendence#60]
- Talvez eslint
- Talvez prettier

**Comment by erick-medeiros** [comment]
blz hehe

**Comment by erick-medeiros** [comment]
Pelo que testei aqui se o index.ts existir o vscode já prioriza o barrel export
Então se fosse existir alguma obrigatoriedade seria de impedir a importação que não seja feita pelo barrel export
E para isso não encontrei alternativas muito viáveis

https://stackoverflow.com/questions/76167422/how-to-force-the-use-of-barrel-files-in-typescript

Encontrei essa ideia mas teria que mudar a estrutura que estamos usando atualmente
