### ISSUE TITLE
Guests expirados e não apagados estão com status online

### ISSUE THREAD

**Issue by erick-medeiros** [tenis-de-mesa/ft_transcendence#64]
![image](https://github.com/tenis-de-mesa/ft_transcendence/assets/49819787/4c0dd1b9-db19-4857-b659-87861fe4d565)

**Comment by araggohnxd** [comment]
que bizarro. na pratica, no produto final, os guests nem vao ter acesso ao chat, ne
mas acho interessante entender a causa do problema

**Comment by LucasKuhn** [comment]
> ![image](https://user-images.githubusercontent.com/49819787/274132238-4c0dd1b9-db19-4857-b659-87861fe4d565.png)

Nessa imagem, dá pra ver os guests na lista de usuários 
Mas se eles tão na lista, como tu sabe que eles tão expirados? 
Pensei que quando era expirado, deletava o user -> Ai ele nem aparece na lista
Por aparecer na lista, não quer dizer que eles não tão expirados?

**Comment by LucasKuhn** [comment]
Se for a questão de enquanto ele tá com a página aberta aparece que ele tá online, dá pro próprio job que apaga o usuário emitir via socket que aquele usuário tá offline 
Fiz isso nessa PR #85

**Comment by erick-medeiros** [comment]
problema reprodutível apenas em ambiente de desenvolvimento
