### ISSUE TITLE
Adicionar um AuthGuard no gateway que recebe sockets

### ISSUE THREAD

**Issue by LucasKuhn** [tenis-de-mesa/ft_transcendence#67]
- Não sei nem se funciona, mas idealmente seria legal se tivesse um authguard que checa se a session é válida no gateway, do mesmo modo que tem no controller aí toda request tá validada
- Outra que seria legal, seria o decorator pegar direto o @User, pra também ficar igual aos controllers  
____ Exemplos:

- https://github.com/adzamkomladev/nest-laze/blob/master/src/chats/chats.gateway.ts
- https://github.com/adzamkomladev/nest-laze/blob/master/src/auth/guards/ws-auth.guard.ts
- https://github.com/adzamkomladev/nest-laze/blob/master/src/auth/strategies/ws-jwt.strategy.ts

**Comment by erick-medeiros** [comment]
A do decorator acho dificil porque como o gateway só recebe a session ele precisa de alguma forma passar pelo serviço que faz a associação do user com o session

**Comment by araggohnxd** [comment]
Não teve `AuthGuard`, mas teve [validação da sessão ativa no `afterInit()` do gateway](https://github.com/tenis-de-mesa/ft_transcendence/blob/e16fc66ff43041e1b194390783e4e4bb56a6cbc3/backend/src/chats/chats.gateway.ts#L41-L50) na PR #126.

https://github.com/tenis-de-mesa/ft_transcendence/blob/e16fc66ff43041e1b194390783e4e4bb56a6cbc3/backend/src/chats/chats.gateway.ts#L107-L117
