### ISSUE TITLE
Order messages

### ISSUE THREAD

**Issue by erick-medeiros** [tenis-de-mesa/ft_transcendence#70]
Após a atualização da foto de perfil a ordem das mensagens mudou para o usuário Guest

visão do usuário eandre-f
![Screenshot from 2023-10-12 14-52-28](https://github.com/tenis-de-mesa/ft_transcendence/assets/49819787/03c19167-043c-49f5-bc3c-5c9c7ccbc40d)

visão do usuário guest

![Screenshot from 2023-10-12 14-52-05](https://github.com/tenis-de-mesa/ft_transcendence/assets/49819787/6c616fb9-d616-4247-9e25-e80001887f6d)

**Comment by LucasKuhn** [comment]
Negócio é cada mensagem ter um createdAt e ordenar as mensagens pela ordem de criação 
Também é legal pra mostrar a hora que a mensagem foi enviada
