### ISSUE TITLE
Problema de atualizacao dos chats (react-router)

### ISSUE THREAD

**Issue by ichmi** [tenis-de-mesa/ft_transcendence#81]
Estamos enfrentando um problema onde os chats nao estao sendo devidamente atualizados ao clicar em um respectivo chat da listaa de chats. O problema eh que, quando navegamos para uma nova rota usando `<Link to={"/chats/" + id} />`, o componente de chat correspondente n esta sendo atualizado com a nova informacao... A menos que a pagina seja completamente recarregada.

#### Duas possiveis solucoes provisorias seriam:
- Usar a tag de ancora: `<a href={"/chats/" + id}>...</a>` da qual recarregara a page
- Passar uma segunda propriedade (`reloadDocument`) para o componente `Link` 

Porem, acredito que ambas opcoes ferem o conceito de uma SPA. 

#### Passos para reproduzir:
- Criar multiplas instancias de chat
- Clique nos links de chat 
Observe que os dados do chat n sao atualizados, porem a URL eh ajustada e armazenada no historico.

#### Comportamento esperado:
Quando eu clico em um chat na lista, o componente de chat (`<Chat />`) correspondente deve ser atualizado com as novas informacoes sem que a page seja recarregada.

#### Notas adicionais:
Tentei rerenderizar o componente usando hooks do react-router como `useLocation`, `useHistory`, e tambem `useEffect`. Acredito que o problema esteja no setup das rotas com `createBrowserRouter` no arquivo `router.tsx`. Pois atualmente ele so esta renderizando o componente `Chat` na primeiraa vez que o acessaamos e nao de forma dinamica.

**Comment by erick-medeiros** [comment]
Acredito que essa issue é uma boa oportunidade para mudar a organização do roteamento para ser feito por componente e não por objeto
