### ISSUE TITLE
status offline após refresh

### ISSUE THREAD

**Issue by erick-medeiros** [tenis-de-mesa/ft_transcendence#93]
![image](https://github.com/tenis-de-mesa/ft_transcendence/assets/49819787/b4a19b73-6235-48a6-9981-cc44eede365b)

Se clicar em `All users` e der refresh na página o usuário logado fica com status offline

**Comment by erick-medeiros** [comment]
![image](https://github.com/tenis-de-mesa/ft_transcendence/assets/49819787/a5547ac7-aba9-4cff-b0a9-7f4c3adccf51)

substituir isso por um socket.on

**Comment by LucasKuhn** [comment]
O que acha de sempre que listar o /user devolver que o próprio usuário que pediu a lista tá online? Back resolve e funciona pra todos

**Comment by LucasKuhn** [comment]
Entendi o problema, e porque só acontece as vezes: 
É uma race condition entre o conectar do Socket e o Load Users 
O socket conecta, atualiza o user pra online, e enquanto isso o front ja tá carregando a lista de usuários
Se a chamada do socket for mais rápido -> A listagem de users dá que o usuário tá online
Se a listagem for mais rápida -> A listagem pega o user ainda offline enquanto o socket tá conectando o dizendo que o user tá online 

Minha sugestão é o front ser otimístico e presumir que o usuário atual está online - testei aqui e resolve o problema.
PR ->  #96
